import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import "./globals.css";
import { Inter } from "next/font/google";
import { NextAuthProvider } from "./Providers";
import { AudioProvider } from "./AudioContext";
import { TabsProvider } from "./TabsContext";


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "My Music Store",
  description: "Generated by create next app",
  
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
<head>
<script async src="https://tally.so/widgets/embed.js"></script>


</head>
      <body className={inter.className}>
        <NextAuthProvider>
          <AudioProvider>
            <TabsProvider>
          <div className="flex flex-col h-screen max-h-screen">
            <Navbar />
            <div className="flex-grow overflow-y-auto bg-page text-default-text">
      
      {children}
    

 
    </div>

   <Footer/>
          </div>
          </TabsProvider>
          </AudioProvider>
        </NextAuthProvider>
    
      </body>
    </html>
  );
}
